### ISSUE TITLE
Define person Model/Entity

### ISSUE THREAD

**Issue by tedsinc** [tedsinc/ping-pong-tournament#6]

**Comment by paddockt** [comment]
Does this connect to the MongoDB?

**Comment by paddockt** [comment]
Connected to #14

**Comment by AnthonyRinaldi** [comment]
Negatory, this is just the data model for person.

**Comment by paddockt** [comment]
10-4

On Wed, Mar 4, 2015 at 2:53 PM, AnthonyRinaldi <notifications@github.com>
wrote:

> Negatory, this is just the data model for person.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tedsinc/ping-pong-tournament/issues/6#issuecomment-77233037>
> .
>



-- 
Tristan Paddock

Senior Software Engineer
TEDS, Inc. <http://www.teds.com/>
tristan.paddock@teds.com
